### ISSUE TITLE
Loading hangs by 76%

### ISSUE THREAD

**Issue by LightRO** [sant0ro/chocolatey#223] opened 2017-05-07 21:37 UTC
Hello everybody,

I have a problem and when I go to hotel he loads only up to 76% after that happens nothing more.

Server ip as well as all paths are entered correctly.
What could be the problem?

**Comment by sant0ro** [comment] 2017-05-07 21:41
Hi @LightRO!

Thanks for reporting an Issue to the **Chocolatey Repository**.

We're glad that you're using our software. I need to remember that **this** message was generated automatically.

In order to **gracefully** report your Issue, please we recommend the followance of those requirements:

Here's what to do: if you need help:

* Inform a complete message of your problem, and what's happening.
* Attach your **lumen.log** if it exists.
* Attach images of the reported bugs/glitches.
* Attach also Information about Operational System, Web Server, PHP Versiom, and other infos.
* Explain what you tried and how tried.

Recommendations About your recently opened Issue?
--------------------------------

We really recommend using [Lightshot](https://app.prntscr.com/pt-br/download.html) to take your screenshot. It allows marks, annotations and more.

If you bug it's about a feature from **Chocolatey** or glitch, we **trully** recommend taking a **HAR File**. You can attach a [HAR File following this procedure](https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-).

A **HAR** file it's a complete log of the network requests of a specific page.

Also we recommend specify some Informations about your **OS** like.:

* Operational System
* Which Web Server are you using (like XAMPP)
* Which version of Web Server Using (eg.: 1.7.3)
* Which version of php & mysql & apache using. (Specify if is possible)
* How much RAM does you have?

Are you creating a Feature Request?
------------------------------

About Feature requests, we recommend you specify completely about what your **Feature Request** is. Tag the type of change that you want to be added.

Changes need to be specified, and you need specify why and what you want to be changed/added.

Be creatively and try explain in the best manner as possible.

Tag the Issue on the Title
-------------------------------

Tagging your Issue will be the best thing you can do for us. We separate issues by tags, and we can work more quickly by knowing from what is the Issue related.

**Those are the available tags:**

* Security
* Angular
* Feature Request
* Server Error
* HabboWEB Glitch
* Translation Mistake
* CSS Mistake/Glitch
* Feature not Working
* Help Wanted
* Can't Install
* Urgent Issue
* Game Bug
* Migration Bug
* Upgrading Bug

**Remember to tag on the title of the Issue [_Issue Type_]**

I updated my Issue.. And now?
---------------------------

You wait.

We have **ful-jobs** and a **life**, we will receive updates by e-mail and soon as possible update your **Issue** by tagging it correctly, assigning to our team and **obviously** answering it.

Then we will support you and help you in what we can.

Also if you Issue it's out of the **params** we will not answer it, or answer it **asking to you fix and correct the main message**

If you dom't know how to use GitHub correctly, check [this](https://guides.github.com/features/issues/) tutorial.

Further information
-------------------

* This **BOT** was originally created by @ajdlinux and @daxtens.
* Edited by @sant0ro for own purposes.
* Contributors of Chocolatey @BobyTS and @s150217754

**Comment by LightRO** [comment] 2017-05-08 06:03
Hello everybody,

My lumen.log has no content after I have eliminated all DB errors.

OS: Ubuntu 14.04 LTS
Web: Apache 2 / PHP 7.1
MySQL 5.5.55

The console says:
`  Welcome to Chocolatey the ultimate experience with RKW Club HotelWEB. We
  from Chocolatey team wish to you a good experience with it. Report bugs
  on our GitHub (https://github.com/sant0ro/Chocolatey).
                                                                              
                                                                   - Chocolatey
habboapi.js:148 action = [clientload], label = [client.init.start], value = [undefined]
habboapi.js:148 action = [clientload], label = [starting], value = [Initalizing Habbo Client.]
habboapi.js:148 action = [clientload], label = [web.view.start], value = [undefined]
habboapi.js:148 action = [clientload], label = [client.init.swf.loaded], value = [undefined]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 0/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 2520/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 3780/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 6300/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 7560/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 8820/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 10080/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 11340/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 0/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 1260/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 2520/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 5040/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 6300/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 7560/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 8820/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 10080/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 11340/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 11340/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 12600/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 15120/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 17640/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 21420/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 23940/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 26460/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 27720/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 28980/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 11340/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 12600/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 15120/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 19216/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 21420/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 22680/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 23940/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 27720/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 28980/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 30240/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 34336/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 39060/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 42840/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 45360/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 47880/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 54180/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 27720/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 31500/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 37800/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 45360/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 46620/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 50400/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 51660/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 54180/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 55440/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 57960/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 59220/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 67412/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 68040/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 73080/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 75600/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 80640/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 81900/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 83160/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 51660/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 54180/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 55440/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 60480/62005]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 61740/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 62005/62005]
habboapi.js:148 action = [log], label = [debug], value = [Load event INIT for file "hh_human_body.swf"]
habboapi.js:148 action = [log], label = [debug], value = [Load event STATUS 200 for file "hh_human_body.swf"]
habboapi.js:148 action = [log], label = [debug], value = [Load event COMPLETE for file "hh_human_body.swf"]
habboapi.js:148 action = [log], label = [debug], value = [Analyzing library "hh_human_body", content is not a MovieClip]
habboapi.js:148 action = [log], label = [debug], value = [	Bytes loaded: 62005/62005]
habboapi.js:148 action = [log], label = [debug], value = [Preparing library "hh_human_body"]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 83160/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 85680/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 89460/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 90720/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 94500/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 100800/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 107100/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 109620/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 117180/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 123480/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 124740/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 133560/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 141120/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 142380/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 146160/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 149940/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 158760/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 162540/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 166320/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 171360/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 172620/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 173880/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 175140/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 176400/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 180180/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 183960/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 186480/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 192780/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 197820/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 201600/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 206640/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 211680/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 214200/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 216720/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 219240/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 221760/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 223020/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 226800/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 228060/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 229320/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 235620/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 236880/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 238140/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 239400/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 243180/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 249480/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 252000/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 260820/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 267120/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 273420/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 278460/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 279720/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 283500/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 289800/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 294840/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 297360/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 302400/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 306180/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 311220/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 312480/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 317520/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 318780/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 320040/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 321300/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 322560/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 323820/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 325080/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 326340/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 331380/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 335160/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 336420/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 338940/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 343980/349781]
2habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 347760/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 349781/349781]
habboapi.js:148 action = [log], label = [debug], value = [Load event INIT for file "hh_human_item.swf"]
habboapi.js:148 action = [log], label = [debug], value = [Load event STATUS 200 for file "hh_human_item.swf"]
habboapi.js:148 action = [log], label = [debug], value = [Load event COMPLETE for file "hh_human_item.swf"]
habboapi.js:148 action = [log], label = [debug], value = [Analyzing library "hh_human_item", content is not a MovieClip]
habboapi.js:148 action = [log], label = [debug], value = [	Bytes loaded: 349781/349781]
habboapi.js:148 action = [log], label = [debug], value = [Preparing library "hh_human_item"]
habboapi.js:148 action = [clientload], label = [client.init.core.init], value = [undefined]`

**Comment by sant0ro** [comment] 2017-05-08 12:27
Okay, as far I see, you're somehow in someplace repeating the url's in your console log if you see the crossdomain.xml url is http://http// that shouldn't happen.

Check in your chocolatey configurations if all urls of the swf are right.

Remember.: crossdomain.xml it's essential.
Also maybe the problem isn't it, but check it first.

**Comment by sant0ro** [comment] 2017-05-08 12:28
Okay as far I see, the assets loading are right.

Check if the port it's open.
Also don't forget the listen ip on arcturus need to be 0.0.0.0, not 127.0.0.1

Anyways, I would strongly recommend you to create Arcturus related Issues on RaGEZONE.

**Comment by LightRO** [comment] 2017-05-08 13:34
i become following message in the console:

[PACKET][CLIENT][4000] => [0]!PRODUCTION-201701242205-837386173[0][5]FLASH[0][0][0][1][0][0][0][0]
[PACKET][CLIENT][UNDEFINED][3392] =>

can that helped you?

**Comment by s150217754** [comment] 2017-05-08 14:34
You are using a wrong Production (wrong version of Habbo.swf). 

Arcturus is targeted to PRODUCTION-201611291003-338511768 which Habbo.swf can be obtained from Arcturus' BitBucket page. 

Closing this as we do not provide support for non CMS issue.

**Closed by s150217754** 2017-05-08 14:34 UTC
