### ISSUE TITLE
 [Help Wanted] Privacy page

### ISSUE THREAD

**Issue by lifelies** [sant0ro/chocolatey#218] opened 2017-05-01 11:46 UTC
im noob pls dont get mad jk okay well when i try to go to XXX.XX/settings/(privacy) i get the 404 page.

pls help xox

![b9e7796531a14527a932c805045c6829](https://cloud.githubusercontent.com/assets/28258294/25579034/8c8d7026-2e74-11e7-847e-47a55556ccc1.png)

**Comment by sant0ro** [comment] 2017-05-01 11:47
Hi @lifelies!

Thanks for reporting an Issue to the **Chocolatey Repository**.

We're glad that you're using our software. I need to remember that **this** message was generated automatically.

In order to **gracefully** report your Issue, please we recommend the followance of those requirements:

Here's what to do: if you need help:

* Inform a complete message of your problem, and what's happening.
* Attach your **lumen.log** if it exists.
* Attach images of the reported bugs/glitches.
* Attach also Information about Operational System, Web Server, PHP Versiom, and other infos.
* Explain what you tried and how tried.

Recommendations About your recently opened Issue?
--------------------------------

We really recommend using [Lightshot](https://app.prntscr.com/pt-br/download.html) to take your screenshot. It allows marks, annotations and more.

If you bug it's about a feature from **Chocolatey** or glitch, we **trully** recommend taking a **HAR File**. You can attach a [HAR File following this procedure](https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-).

A **HAR** file it's a complete log of the network requests of a specific page.

Also we recommend specify some Informations about your **OS** like.:

* Operational System
* Which Web Server are you using (like XAMPP)
* Which version of Web Server Using (eg.: 1.7.3)
* Which version of php & mysql & apache using. (Specify if is possible)
* How much RAM does you have?

Are you creating a Feature Request?
------------------------------

About Feature requests, we recommend you specify completely about what your **Feature Request** is. Tag the type of change that you want to be added.

Changes need to be specified, and you need specify why and what you want to be changed/added.

Be creatively and try explain in the best manner as possible.

Tag the Issue on the Title
-------------------------------

Tagging your Issue will be the best thing you can do for us. We separate issues by tags, and we can work more quickly by knowing from what is the Issue related.

**Those are the available tags:**

* Security
* Angular
* Feature Request
* Server Error
* HabboWEB Glitch
* Translation Mistake
* CSS Mistake/Glitch
* Feature not Working
* Help Wanted
* Can't Install
* Urgent Issue
* Game Bug
* Migration Bug
* Upgrading Bug

**Remember to tag on the title of the Issue [_Issue Type_]**

I updated my Issue.. And now?
---------------------------

You wait.

We have **ful-jobs** and a **life**, we will receive updates by e-mail and soon as possible update your **Issue** by tagging it correctly, assigning to our team and **obviously** answering it.

Then we will support you and help you in what we can.

Also if you Issue it's out of the **params** we will not answer it, or answer it **asking to you fix and correct the main message**

If you dom't know how to use GitHub correctly, check [this](https://guides.github.com/features/issues/) tutorial.

Further information
-------------------

* This **BOT** was originally created by @ajdlinux and @daxtens.
* Edited by @sant0ro for own purposes.
* Contributors of Chocolatey @BobyTS and @s150217754

**Comment by sant0ro** [comment] 2017-05-01 16:15
Hi @lifelies if possible can you attach the `lumen.log` file, and give more detailed information of what is happening?

Off: No problem of being noob :)

**Comment by sant0ro** [comment] 2017-05-01 16:25
Observation.: I don't know what is happening on your Chocolatey. Which version are you using?

**Comment by lifelies** [comment] 2017-05-01 16:27
im using the latest noobfriendly version and it first worked okay but when i tried it today it could not find the page at all and i didnt edit or anything

**Comment by lifelies** [comment] 2017-05-01 22:04
https://pastebin.com/Q4Q7RYx1

couldnt upload it

**Comment by sant0ro** [comment] 2017-05-02 12:36
Does you already tried logout your user and login again?

**Comment by sant0ro** [comment] 2017-05-02 12:46
It seems that you're using Chocolatey in a wrong way.

One first question, does this account has an entry on the table `chocolatey_users_preferences`?

Does this account was registered with Chocolatey?
Does you updated your Chocolatey (some logs are inconsistent for latest version)

Can you provide more information on what happened? I recommend a fresh install.

**Comment by lifelies** [comment] 2017-05-02 12:55
Oh my gawd, its because my account is not registered via Chocolatey. Thanksss! All that matters is that users can use it. Thankss.

**Comment by sant0ro** [comment] 2017-05-02 13:01
Anyways, I'm going to create a fix that automatically will compatibilize the accounts :)

**Comment by sant0ro** [comment] 2017-05-02 13:02
Observation.: If you're using Chocolatey 3000D it wouldn't be possible login without a Chocolatey created account. Since the auth isn't anymore directly on users table.

**Comment by lifelies** [comment] 2017-05-02 13:04
I created another account and just changed the email and for my account that's why the /settings/privacy  isn't working anymore I guess, but the other setting pges are working fine, haha

**Comment by sant0ro** [comment] 2017-05-02 13:07
So, the issue is fixed? Remember, if you change the e-mail, you need change both on `chocolatey_users_id` and `users` tables.

**Comment by lifelies** [comment] 2017-05-02 13:13
Yeh, new users don't have the problem and when I'm home I'll try the database thing you just said. Hope it works and otherwise for me the other setting links work except privacy. Thanks for the great service, tho.

**Comment by sant0ro** [comment] 2017-05-02 13:33
No problem, I'll close the issue after you doing those checks.

**Comment by s150217754** [comment] 2017-06-10 17:32
Hello @lifelies,

Please let us know if you have resolved this issue. We will be closing this Issue in a few hours if we do not receive any response from your end. Thank you.

**Comment by sant0ro** [comment] 2017-06-10 18:57
Exactly, it's seems a really big time since he created the Issue.

**Comment by s150217754** [comment] 2017-06-11 06:52
Closed. Feel free to re-open should you continue to face the **same** issue.

**Closed by s150217754** 2017-06-11 06:52 UTC
